apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "releasehub360.labels" . | nindent 4 }}
    app.kubernetes.io/component: n8n
spec:
  type: {{ .Values.n8n.service.type }}
  selector:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.n8n.service.port }}
      targetPort: {{ .Values.n8n.port }}
