apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "releasehub360.labels" . | nindent 4 }}
data:
  NODE_ENV:       {{ .Values.backend.env.nodeEnv | quote }}
  N8N_URL:        {{ .Values.backend.env.n8nUrl | quote }}
  MCP_SERVER_URL: {{ .Values.backend.env.mcpServerUrl | quote }}
  TFS_ORG_URL:    {{ .Values.secrets.tfsOrgUrl | quote }}
  DATABASE_URL:   {{ printf "postgresql://%s:%s@postgres:%d/%s" .Values.postgres.user .Values.postgres.password ( .Values.postgres.port | int ) .Values.postgres.database | quote }}
